feat(archive account): add account archiving feature
widefix/pocketmoney pull request #124
Opened 2023-09-21 16:10 UTC by VladislavSokov

2023-09-21 16:38 UTC, ka8725 commented on app/controllers/accounts_controller.rb
> +    end
it should just raise active record not found, i.e. fix the code so that it finds with "!" on a specific scope.

2023-09-21 16:38 UTC, ka8725 commented on app/controllers/accounts_controller.rb
> +    AccountAutomaticTopupConfig.where(to_account: account).delete_all
let's also archive `AccountAutomaticTopupConfig`

2023-09-21 16:40 UTC, ka8725 requested changes

2023-09-21 16:40 UTC, ka8725 commented on app/models/account.rb
> +  has_many :children, -> { where(archived_at: nil) }, class_name: 'Account', foreign_key: :parent_id
create a scope `unarchived` and use it here and below.

2023-09-21 16:40 UTC, ka8725 commented on app/controllers/accounts_controller.rb
> +  rescue ActiveRecord::RecordNotFound
Why catch it?

2023-09-22 08:01 UTC, ka8725 commented on app/controllers/accounts_controller.rb
> +    AccountAutomaticTopupConfig.where(to_account: account).delete_all
@VladislavSokov I have a better idea. Let's not change anything except the account. However, the place that selects the top-up configurations should be changed to filter those related to deleted accounts.

2023-09-22 21:36 UTC, ka8725 commented on app/controllers/accounts_controller.rb
> +    AccountShare.where(account_id: account).delete_all
Why this is needed? We should change only the account here. All other related data, if it affects the system, should definitely be disabled. But it should be disabled only by filtering, e.g. checking if the related account is not archived.

2023-09-22 21:38 UTC, ka8725 requested changes
@VladislavSokov archived accounts should be excluded here too - https://github.com/widefix/pocketmoney/blob/9eab14933fbdca1820b99bd9cfc366d59035f700/lib/tasks/scheduler.rake#L4C5-L4C32

2023-09-25 20:57 UTC, ka8725 commented on app/models/account_automatic_topup_config.rb
> +  scope :active, -> { where(to_account: { archived_at: nil }) }
```suggestion
  scope :visible, -> { where(to_account: { archived_at: nil }) }
```

2023-09-25 20:57 UTC, ka8725 commented on app/models/account_share.rb
> +  scope :active, -> { includes(:account).where(accounts: { archived_at: nil }) }
```suggestion
  scope :visible, -> { includes(:account).where(accounts: { archived_at: nil }) }
```

2023-09-26 08:56 UTC, andreybakanovsky approved these changes

2023-09-26 09:59 UTC, ka8725 approved these changes

2023-09-26 09:59 UTC, merged