feat(goals notification): add goals almost achieved notification
widefix/pocketmoney pull request #204
Opened 2023-10-17 16:57 UTC by VladislavSokov

2023-10-18 07:36 UTC, ka8725 requested changes
Good work in general, but we need to reuse existing code if possible

2023-10-18 07:36 UTC, ka8725 commented on app/models/objective.rb
> +  scope :visible, -> { joins(:account).where(account: { archived_at: nil }) }
Can we a scope here to select not archived

2023-10-18 07:36 UTC, ka8725 commented on app/services/objective_notification_service.rb
> +      total_weeks_left = ([objective_amount - account_balance, 0].max / automatic_topup_amount).to_i
Can we reuse the calculations used in the objectives table? I mean is there a DRY solution?

2023-10-18 07:36 UTC, ka8725 commented on db/migrate/20231017134708_add_notified_for_objectivites.rb
> +    add_column :objectives, :goal_almost_achieved_notified, :boolean, default: false
Let's use time stamps instead of Boolean for these fields

2023-10-19 08:29 UTC, ka8725 requested changes

2023-10-19 08:29 UTC, ka8725 commented on app/actions/week_to_goal_action.rb
> +    return 999 if objective.account.automatic_topup_configs.blank?
If it's blank, this number does not make sense. But 999 does make sense. Can we return something that does not make sense instead of 999?

2023-10-19 08:29 UTC, ka8725 commented on app/mailers/objectives_mailer.rb
> +    mail to: account_share&.email || @user.email, title: "Goal #{@objective} achived"
See here how to send email to multiple recipients - https://stackoverflow.com/a/7437303

2023-10-19 08:29 UTC, ka8725 commented on app/mailers/objectives_mailer.rb
> +    mail to: account_share&.email || @user.email, title: "Goal #{@objective} almost achived"
See here how to send email to multiple recipients - https://stackoverflow.com/a/7437303

2023-10-19 08:29 UTC, ka8725 commented on app/services/objective_notification_service.rb
> +  def check_almost_achieved(objective, total_weeks_left)
The main responsibility of this method is not checking. It actually **sends** almost achieved emails. The method name should be changed respectively.

2023-10-19 08:29 UTC, ka8725 commented on app/views/objectives_mailer/objectives_achieved.html.slim
> +p Congratulations! Your kid #{@name} has achieved the goal: #{@objective}.
```suggestion
p Congratulations! Your kid <a>#{@name}</a> has achieved the goal <a>#{@objective}</a>. 
p Now, you can buy <a>#{@objective}</a> and delete it from the active goals.
p The current balance on your kid's <a>account</a> is $#{@balance}.
```

Replace <a> with dynamic links.

2023-10-19 08:29 UTC, ka8725 commented on app/views/objectives_mailer/objectives_almost_achieved.html.slim
> +p Your kid needs $#{@amount} to achieve this goal.
Use links here as well.

2023-10-19 08:29 UTC, ka8725 commented on app/views/objectives_mailer/objectives_almost_achieved.html.slim
> +p Your kid, #{@name}, has 1 week left to reach the goal: #{@objective}.
```suggestion
p Your kid, #{@name}, has 1 week left to reach the goal <a>#{@objective}</a>.
```

2023-10-19 08:29 UTC, ka8725 commented on app/views/objectives_mailer/objectives_almost_achieved.html.slim
> +p The current balance on your kid's account is $#{@balance}.
```suggestion
p The current balance on your kid's <a>account</a> is $#{@balance}.
```

2023-10-19 08:29 UTC, ka8725 commented on db/migrate/20231018113402_change_objective_fields_to_dates.rb
> +    add_column :objectives, :goal_achieved_notified_to, :datetime, default: nil
```suggestion
    add_column :objectives, :goal_achieved_notified_at, :datetime, default: nil
```

2023-10-19 08:29 UTC, ka8725 commented on db/migrate/20231018113402_change_objective_fields_to_dates.rb
> +    add_column :objectives, :goal_almost_achieved_notified_to, :datetime, default: nil
```suggestion
    add_column :objectives, :goal_almost_achieved_notified_at, :datetime, default: nil
```

2023-10-19 08:29 UTC, ka8725 commented on db/migrate/20231018113402_change_objective_fields_to_dates.rb
> +class ChangeObjectiveFieldsToDates < ActiveRecord::Migration[6.1]
It's ok to rollback and rework migrations while it's in dev. No need to create new one.

2023-10-19 19:01 UTC, ka8725 requested changes
Nice work! We are getting to the finish state.

2023-10-19 19:01 UTC, ka8725 commented on app/views/accounts/show.html.slim
> +          h3.title.is-4#objective Objectives
Why it's needed?

2023-10-19 19:01 UTC, ka8725 commented on app/models/objective.rb
> +  def calculate_week_to_achived
Also, cover this method by specs?

2023-10-20 14:48 UTC, ka8725 commented on app/models/objective.rb
> +  def week_to_achieved
```suggestion
  def weeks_to_achieve
```

2023-10-20 14:53 UTC, ka8725 approved these changes

2023-10-20 15:03 UTC, VladislavSokov commented on app/views/accounts/show.html.slim
> +          h3.title.is-4#objective Objectives
It's for anchor

2023-10-20 15:14 UTC, andreybakanovsky approved these changes

2023-10-22 10:51 UTC, merged