feat(accumulative balance): introduce scale change: by day, by week, by month
widefix/pocketmoney pull request #262
Opened 2023-11-10 16:01 UTC by VladislavSokov

![Screenshot from 2023-11-10 18-53-08](https://github.com/widefix/pocketmoney/assets/62177364/9c53eaa5-afbd-4f82-8723-16238fcba0fa)
![Screenshot from 2023-11-10 18-53-21](https://github.com/widefix/pocketmoney/assets/62177364/f5c1bc3d-a697-4ded-87e4-4d04cadf692f)

2023-11-11 12:20 UTC, VladislavSokov commented
![Screenshot from 2023-11-11 15-15-28](https://github.com/widefix/pocketmoney/assets/62177364/9b873bb7-fff1-493b-a03b-29b3f27d0df1)
![Screenshot from 2023-11-11 15-15-41](https://github.com/widefix/pocketmoney/assets/62177364/271634b6-48e8-4564-a21a-e44eb2722a9b)
![Screenshot from 2023-11-11 15-16-14](https://github.com/widefix/pocketmoney/assets/62177364/56c10ca4-8f32-4b4b-b212-4571ce7caea2)
![Screenshot from 2023-11-11 15-16-32](https://github.com/widefix/pocketmoney/assets/62177364/a9484d9d-9620-4e5b-bbc6-e8d65cd5c792)

2023-11-11 13:24 UTC, VladislavSokov commented
![Screenshot from 2023-11-11 16-22-25](https://github.com/widefix/pocketmoney/assets/62177364/0c45ff2c-0bb1-41af-9437-9d396ce29428)
![Screenshot from 2023-11-11 16-22-16](https://github.com/widefix/pocketmoney/assets/62177364/927aad86-28ac-423f-bb1d-31b7788884e2)
![Screenshot from 2023-11-11 16-21-55](https://github.com/widefix/pocketmoney/assets/62177364/42049bd2-af44-4b9d-88c3-4e87c1a4cf2b)
![Screenshot from 2023-11-11 16-21-43](https://github.com/widefix/pocketmoney/assets/62177364/151735a9-4273-48ac-9bb0-21706a7cc828)

2023-11-12 16:20 UTC, ka8725 commented on db/schema.rb
> +    t.string "accumulative_balance_timeframe", default: "day"
This is a user option but not account.

Let's move the persistence issue to a separate task. We should create `UserAccountSettings` model and keep this kind of data there.

2023-11-12 16:21 UTC, ka8725 requested changes
Great job! It works like expected, but let's move the persistence issue into a separate PR.

2023-11-13 21:39 UTC, andreybakanovsky commented on spec/models/account_spec.rb
> +      create(:transaction, to_account: parent, from_account: child, amount: 70.0, created_at: 1.week.ago)
`let(:store) { create(:account, :store) }` -> `to_account: store`
more clear ;)

2023-11-13 21:40 UTC, andreybakanovsky approved these changes

2023-11-13 22:17 UTC, ka8725 approved these changes

2023-11-13 22:17 UTC, merged