fet(account_invitation): create access logic
widefix/pocketmoney pull request #28
Opened 2023-08-25 14:02 UTC by VladislavSokov

2023-08-25 14:06 UTC, ka8725 commented on app/views/my_accounts/show.html.erb
> +<% accounts.each do |account| %>
I have another idea - what if we just put a section below called **Shared accounts** and list these shared accounts there?

Also, later we could show not accepted invitations there as well (creating a ticket for that)

2023-08-25 16:00 UTC, andreybakanovsky approved these changes

2023-08-25 16:42 UTC, ka8725 requested changes

2023-08-25 16:42 UTC, ka8725 commented on app/controllers/my_accounts_controller.rb
> +  end
```ruby
helper_method memoize def shared_accounts
  Account.invitees(current_user)
end
```

2023-08-25 16:42 UTC, ka8725 commented on app/models/account.rb
> +               AccountInvitation.accepted.for(current_user).pluck(:account_id))
```suggestion
               invitees(current_user).pluck(:id)
```

2023-08-25 16:42 UTC, ka8725 commented on spec/controllers/my_accounts_spec.rb
>  RSpec.describe MyAccountsController, type: :controller do
add a test to check the shared accounts

2023-08-28 15:04 UTC, VladislavSokov commented on .rubocop_todo.yml
> +# on 2023-08-25 14:11:22 UTC using RuboCop version 1.56.0.
I fix all linter warnings in every file I work on. And since these warnings are fixed, I remove them from to_do

2023-08-28 17:21 UTC, ka8725 approved these changes

2023-08-28 17:22 UTC, merged